# Array Indexing

In [28]:
import numpy as np

# Numpy Indexing & Slicing of Array

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[4]

15

In [6]:
#slicing means remove any pStopIteration

arr[1:4]

#for last element it is n+1

array([12, 13, 14])

In [8]:
arr[:5]
#default is first value

array([11, 12, 13, 14, 15])

In [11]:
arr[4:]
# default is last value

array([15, 16, 17, 18, 19, 20])

In [10]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[3::2]

# here 2 is steps

array([14, 16, 18, 20])

In [13]:
# we save it in to somewhere
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

# Numpy Indexing And Slicing of Matrix

In [16]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
# for rows
arr[0]

array([1, 2, 3, 4, 5])

In [18]:
arr[5]

array([26, 27, 28, 29, 30])

In [19]:
# for particulaar element

arr[0,0]

1

In [20]:
arr[5,4]

30

In [22]:
# slicing means remove particular portion 
# to slice 2,7,3,8

slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [23]:
slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
#or
slice=arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [25]:
# for selecting column

arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [30]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
# we check the number is even or not
bool_index =arr % 2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
#now we assign boolean to array

arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])