# Array operations

In [2]:
import numpy as np

# Arithmatic Operations

In [11]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

# while performing operations the arrays size should be same

In [12]:
a1

array([1, 2, 3, 4, 5])

In [13]:
a2

array([ 6,  7,  8,  9, 10])

In [14]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [15]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1//a2

array([0, 0, 0, 0, 0])

In [19]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# Brodcasting

In [27]:
l=[10,20,30,40,50]
arr = np.array(l)

In [28]:
arr + 10

array([20, 30, 40, 50, 60])

In [30]:
# for brodcasting in matrix 
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
# for save it in to so we can save it
arr2= arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [33]:
# when we see firt arr2 code then we see it will change value

# Deep and shallow copy

In [17]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [6]:
a
#there are no change in array this is the copy of shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
a[4:6]*10


array([50, 60])

In [9]:
a
b=a

In [10]:
b[0]=99

In [11]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
# now there will be also change in a so this is deep copy 

In [22]:
# so if we want that there will be no change in a so we use this method

a1=np.arange(1,21)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a1
b=a1.copy()

In [24]:
b[0]=99

In [25]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
# so we see there will be no change in a1

# Matrix Operations

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
B

array([[5, 6],
       [7, 8]])

In [34]:
# multiplication
A*B
#This is normal matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [35]:
#But this is how the matrix multipication actually

A @ B

# Means 1st row* 1st column and add them

array([[19, 22],
       [43, 50]])

In [36]:
# we also use this for multipication because this is .(dot)multiplication

np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [37]:
# Now we do transpose

A

array([[1, 2],
       [3, 4]])

In [38]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

# 1) stacking Array

In [41]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
#there are thee types of stack 
#horizantal stack
# verticle stack
#column stack

In [42]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# 2) splitting array

In [47]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#split has 2 types horizantal ,vertical

In [50]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [53]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [56]:
# so we save in it 

a=np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [57]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
