In [ ]:
import numpy as np

# Basic Array creation

In [2]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [11]:
#list 
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [13]:
# in list we return multiple data types
a=[1,2,3.5,4,"hello"]
a

[1, 2, 3.5, 4, 'hello']

In [15]:
# now we pass list in array

np.array(a)

#we see datatype that means only one data type is there
# now we remove string so every thing convert in  float 

array(['1', '2', '3.5', '4', 'hello'], dtype='<U32')

In [19]:
#list does not support multidimensional

l=[[1,2,3],[4,5,6],[8,9,10]]
l

#its look lik one dimensional

[[1, 2, 3], [4, 5, 6], [8, 9, 10]]

In [20]:
# now we convvert it in to array

np.array(l)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

# Array Generation Function

In [13]:
arr=np.arange(4,11,2)
arr

#arr ne array save hoto

array([ 4,  6,  8, 10])

In [7]:
# to generate zeros

arr= np.zeros(6)
arr


array([0., 0., 0., 0., 0., 0.])

In [8]:
#now we create matrix
arr= np.zeros((6,6))
arr

# bracket under bracket is for matix or 2 dimensional array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
#linspace
arr=np.linspace(1,5,10)
arr

#pahila element 1 rahil ani shevtcha element 5 rahil ani tyacha madhe 10 number generate karel  
#ani tyancha madhe space same rahil
  
# linspace is use for same space means linear space

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Random generation function

In [25]:
#radom library is also inbuilt

In [27]:
np.random.rand(10)

#values are between o&1, it is concept of normalization

array([0.4547549 , 0.06796346, 0.33860152, 0.59876377, 0.20605516,
       0.10924684, 0.02890239, 0.79883435, 0.70350961, 0.01308333])

In [32]:
np.random.randn(10)
#this is concept of standardization values coms between -3to+3

array([-0.67222352,  1.01176902,  0.76094371,  0.30582191, -0.15297563,
       -0.53451264,  0.19501045,  0.48824904,  0.18361915, -0.1294898 ])

In [34]:
#when we want to generate any random number then

np.random.randint(5)

4

In [36]:
# when we want to generate multiple random numbers
np.random.randint(10,20,10)

array([17, 15, 11, 10, 18, 12, 17, 13, 12, 15])

# Array Attributes

In [37]:
#there are different types of Attribute
#1)shape 
#2) size 
#3) datatype 
#many more

In [39]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.shape

# tip= attribute cha pudhe bracket nahi lagat direct lihle jatat

(3, 3)

In [42]:
arr.size

9

In [43]:
arr.dtype

dtype('int32')

# Array methods

In [44]:
# there are different types of methods

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.min()

1

In [48]:
arr.max()

9

In [49]:
arr.sum()

45

In [52]:
np.sum(arr,axis=0) #for column

array([12, 15, 18])

In [53]:
np.sum(arr,axis=1) #for row

array([ 6, 15, 24])

In [54]:
arr.mean() #middle value

5.0

In [55]:
arr.std() #standard deviation

2.581988897471611

In [56]:
arr.argmax() #max number cha index

8

In [57]:
arr.argmin() #min number cha index

0

# Reshaping and Resizing

In [58]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [61]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [63]:
# for resizing to save in array

arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])