In [1]:
import numpy as np

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
#over all sum

np.sum(s)

405

In [7]:
# for sum of rows

np.sum(s,axis=1)

#1 because rows are horizantal

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
# sum of columns

np.sum(s,axis=0)

# because colums are vertical

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [12]:
# each and every row and column sum should be same

In [18]:
# when we save it and give condition to check a sudoku 

b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [20]:
 #or we also write

b=np.sum(s,axis=1)
for i in b:
    if i !=45:
        print("sudoku is not valid")
        break
else:
   print ("for rows it is valid")
    


for rows it is valid


In [21]:
# now we check it for 3*3 matrix sum should be 45

In [33]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [34]:
# example 2)

In [35]:
import numpy as np

# Columns: [Math Marks, Science Marks]
data = np.array([
    [18, 75, 87],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [36]:
# get the shape of matrix
data.shape

(5, 3)

In [38]:
#find the average age of students 
np.mean(data[:,0])

18.4

In [40]:
# etract math marks of all student
data[:,1]

array([75, 92, 76, 65, 90])

In [43]:
# find the highest science marks

np.max(data[:,2])

95

In [47]:
# get details of student who scored more than 90

data[data[:,1]>90]

array([[19, 92, 88]])

In [49]:
data


array([[18, 75, 87],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [52]:
# increase math marks of all student by 5 

data[:,1] += 5
data


array([[18, 80, 87],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [57]:
# find how many students are younger than 19 

len(data[data[:,0]<19])

3

In [59]:
# calculate the average marks in each subject (coluns wise)

np.mean(data[:,1:],axis=0)

array([84.6, 85. ])

In [60]:
# get data of student who atleast score 80 in both subjectabs

data[(data[:,1]>=80) & (data[:,2] >=80)]

array([[18, 80, 87],
       [19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [65]:
# Replace all science marks<75 with 0 

data[:,2][data[:,2] <75] = 0
data

array([[18, 80, 87],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])